### ISSUE TITLE
ImportError: cannot import name 'ESpeakNG' from 'espeakng'

### ISSUE THREAD

**Issue by JustNaka** [FlorianEagox/weeablind#11]
i'm on windows with python 3.10 
i have installed espeakng and i added it to the path

Traceback (most recent call last):
  File "C:\Users\checc\Desktop\weeablind\weeablind.py", line 3, in <module>
    from tabs.ConfigureVoiceTab import ConfigureVoiceTab
  File "C:\Users\checc\Desktop\weeablind\tabs\ConfigureVoiceTab.py", line 2, in <module>
    import app_state
  File "C:\Users\checc\Desktop\weeablind\app_state.py", line 1, in <module>
    from Voice import Voice
  File "C:\Users\checc\Desktop\weeablind\Voice.py", line 9, in <module>
    from espeakng import ESpeakNG
ImportError: cannot import name 'ESpeakNG' from 'espeakng' (C:\Users\checc\AppData\Local\Programs\Python\Python310\lib\site-packages\espeakng\__init__.py)
(venv) PS C:\Users\checc\Desktop\weeablind>

**Comment by FlorianEagox** [comment]
Haiya! Thanks so much for reaching out! Let's see if we can get this working. Can you just run the command espeak from inside the directory the project is located?

**Comment by JustNaka** [comment]
when i run the command "espeak" the console give me this error 
![image](https://github.com/FlorianEagox/weeablind/assets/58272916/16cb9f20-6592-4826-90bd-f29262ecbfbc)

but in path there is espeak 
![image](https://github.com/FlorianEagox/weeablind/assets/58272916/9936fd05-ef8a-42da-aadb-b43fd08cb6d9)

**Comment by FlorianEagox** [comment]
Okay, this might be more complicated then this, but sometimes just reopening a new terminal or your editor will just fix that, sometimes windows needs a reboot after a path change. I will do a fresh install of everything on windows and see if I get any kind of error like this and can improve the documentation!

**Comment by JustNaka** [comment]
I tried reinstalling espeak and now when I run this on the folder espeak works but still weablind doesn't work
![image](https://github.com/FlorianEagox/weeablind/assets/58272916/88f7c0c2-2d00-4d45-bbbe-5efa5d64e1c7)

**Comment by JustNaka** [comment]
the path variables updated automatically without me doing anything

![image](https://github.com/FlorianEagox/weeablind/assets/58272916/4cdc62a8-4ae0-4e37-b5b5-070b79ffed3b)

**Comment by FlorianEagox** [comment]
Okay it's good that espeak is working on the CLI. Now could you please give me the error you get when running WeeaBlind? If it's still espeak related, I'll try to fix it later toda with a clean install. Thank you for your patience and testing

**Comment by JustNaka** [comment]
same error 
![image](https://github.com/FlorianEagox/weeablind/assets/58272916/fd5808a3-3f9a-4e2a-ac5d-b21739cc6a36)

**Comment by JustNaka** [comment]
news?

**Comment by ZeppDK** [comment]
hahaha, totally love your update text 🥇
