### ISSUE TITLE
AV detections? 

### ISSUE THREAD

**Issue by MethanJess** [FlorianEagox/weeablind#23]
Hey! congrats on releasing the app! I've just noticed a slight problem that could really throw off new users from using it

The exe file gets detected as malware by 7 different Anti-Virus engines
Do you have any ideas why this is happening? are you sure that the program you used to craft the exe file is even safe? I've never seen this many false-positives on a simple 8mb file before...
![Screenshot 2024-05-14 200419](https://github.com/FlorianEagox/WeeaBlind/assets/152042739/893b18d7-337d-4bfb-8524-aa01b800348a)

**Comment by FlorianEagox** [comment]
Hi there! Thank you so much for looking into this for me! 

That's wack lol I never even really thought to test it. It's built with PyInstaller, and from lots of research about how to suppress the "smart screen" warnings, I've seen that this is a common thing with unlicensed executables.


I would guess that those AV warnings have a lot to do with the fact it bundles a python interpreter into the exe. There are ways to get rid of the flags but I don't completely understand it at this time. I'm very confident that this is something trusted by the community to be safe, but you always have the option to build from source as well.

**Comment by MethanJess** [comment]
thanks for the response. that makes a lot of sense!
