### ISSUE TITLE
cannot import name 'espeakng' from espeakng

### ISSUE THREAD

**Issue by lonelyuniverse** [FlorianEagox/weeablind#4]
Hi nice works,i had a issue with this step on Windows 10 with a python environment,please help me to fix this problem "cannot import name 'espeakng' from espeakng"

thanks in advance

**Comment by darkzbaron** [comment]
wxPython won't install, don't lose your time. I am trying to use it on WSL but Ubuntu 20 does not work either. Trying Ubuntu 18 now for installing libffi6. Good luck and let me know if you do something

**Comment by FlorianEagox** [comment]
Hi @lonelyuniverse This error message means that you need to install espeak on your system and added to your PATH system environment variable 
You can get it here:
https://github.com/espeak-ng/espeak-ng/releases
You will also need the latest version of FFmpeg.

Also, for running natively on Windows 10, I find Python 3.8.10 to be the least error-prone to install everything!

Apologies for the late reply!

**Comment by lonelyuniverse** [comment]
thanks for the reply, I had already added espeak to the path but nothing to do, the error comes back, I also tried installing python on the virtual environment and with conda. Although the espeak folder is found in lib/sitepackages and in the path environment variable continue to give me an error.
